server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
leyou:
  jwt:
    secret: cszmiwen=salt # 登录校验的密钥
    pubKeyPath: D:\Desktop\login\rsa.pub # 公钥地址
    priKeyPath: D:\Desktop\login\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
