server:
  port: 8082
spring:
  application:
    name: search-server
  data:
    elasticsearch:
      cluster-nodes: 192.168.229.140:9300
      cluster-name: elasticsearch
  jackson:
    default-property-inclusion: non_null   #过滤object中null的数据转换成json
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
