server:
  port: 8083
spring:
  application:
    name: goods-web-server
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    port: 5672
    host: 106.13.229.216
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
