server:
  port: 8080
spring:
  application:
    name: item-service
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/hm49
  rabbitmq:
    host: 106.13.229.216
    username: leyou
    password: leyou
    virtual-host: /leyou
    port: 5672   # 默认配置
    template:
      exchange: csz_exchange

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo
